package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"time"

	"github.com/getlantern/systray"
	"golang.org/x/sys/windows/registry"
)

var (
	cmd         *exec.Cmd
	cmdCancel   chan bool
	dir         string
	startOnBoot bool
)

const (
	SW_HIDE = 0
)

const (
	// RegistryKey is the registry key where the startup information is stored
	RegistryKey = `Software\Microsoft\Windows\CurrentVersion\Run`
	// AppName is the name of the application used in the registry
	AppName = "Mieru"
	// ExecutableName is the name of the executable
	ExecutableName = "mieru.exe"
)

func main() {
	cmdCancel = make(chan bool)

	// Get the current directory
	var err error
	dir, err = filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		fmt.Println("Error getting current directory:", err)
		return
	}

	// Load start-on-boot setting from registry
	loadStartOnBoot()

	// Run the commands when the program starts
	runCommands()

	// Initialize system tray
	systray.Run(onReady, onExit)
}

func onReady() {
	// Set the icon from base64 data
	iconData := getTrayIcon()
	systray.SetIcon(iconData)
	systray.SetTooltip("Mieru is running")

	// Create main menu items
	optionsMenuItem := systray.AddMenuItem("Options", "")
	startOnBootItem := optionsMenuItem.AddSubMenuItemCheckbox("Start on Boot", "Start the program automatically on system boot", startOnBoot)
	openFolderMenuItem := optionsMenuItem.AddSubMenuItem("Open Folder", "Open the folder where the program is run from")
	exitItem := systray.AddMenuItem("Exit", "Exit the program")

	// Goroutine to handle menu item clicks
	go func() {
		for {
			select {
			case <-exitItem.ClickedCh:
				stopCommand()
				exitProgram()
			case <-startOnBootItem.ClickedCh:
				startOnBoot = !startOnBoot
				saveStartOnBoot()
				updateStartOnBoot(startOnBootItem)
			case <-openFolderMenuItem.ClickedCh:
				openFolder()
			}
		}
	}()
}

func onExit() {
	// Clean up resources
	cmdCancel <- true
	if cmd != nil && cmd.Process != nil {
		cmd.Process.Kill()
	}
}

func runCommands() {
	// Build and run the first command: mieru.exe apply config config.json
	cmd1 := exec.Command(filepath.Join(dir, ExecutableName), "apply", "config", "config.json")
	cmd1.Dir = dir

	// Hide the console window for the Go program
	hideConsoleWindow(cmd1)

	err := cmd1.Start()
	if err != nil {
		fmt.Println("Error running command 1:", err)
	}

	// Build and run the second command: mieru.exe start
	cmd2 := exec.Command(filepath.Join(dir, ExecutableName), "start")
	cmd2.Dir = dir

	// Hide the console window for the Go program
	hideConsoleWindow(cmd2)

	// Run the second command asynchronously
	go func() {
		err := cmd2.Run()
		if err != nil {
			fmt.Println("Error running command 2:", err)
		}
	}()

	// Wait for a short duration (adjust as needed)
	time.Sleep(time.Second)
}

func exitProgram() {
	systray.Quit()
}

func getTrayIcon() []byte {
	// Base64-encoded icon data
	iconBase64 := `AAABAAMAEBAAAAEAIABoBAAANgAAACAgAAABACAAKBEAAJ4EAAAwMAAAAQAgAGgmAADGFQAAKAAAABAAAAAgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJE5BTGPNAG9UiUAv1YjADIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfz8/BI0zAIWONQD7oVMm/21CIP9SIgD8UyMAhz8APwQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiToADY81AbuROQP/xJZ5//jq0f/q0q7/oIVn/1UnBf9UIwG8SDYADgAAAAAAAAAAAAAAAAAAAAAAAAAAnz8fCI80AMOVPwz/3cOv//vcm///tw7/+XsP//C6gv/EsZP/XC8N/1MjAMRUOBwJAAAAAAAAAAAAAAAAAAAAAI42AJqSOwb/4cm2//zVdv//swH//rMB//h0A//5dAL/86pm/8i2mf9YKgj/UiQBmwAAAAAAAAAAAAAAAJAzADyONQD+zKWL//3Ziv/+swD//rIB//+zAf/4dAL/+HQD//h0Av/wsnT/rJJ0/1MlAP5WJQA+AAAAAAAAAACPNQGyoFcp//rqzP//tAf//7IA//+yAP/9uRf/+XQD//h1A//5dQP/+HcJ/+3Rq/9uRST/UyEBtAAAAACZMzMFjjQB+Midg//9zmb//rIA//60Av/73ZT/++zV//eDHP/5dAP/+XQD//h1A//zpVj/p4xt/1MiAfhVKgAGlDUKGI40Af/ZuaX//MM6//6yAP/735r/+t2a//zLUv/v0qz/94Eb//h0A//5dAL/9ZA1/7ymi/9SJAD/WB0JGo4yABmONQD/2Lqn//zCOf/+swD//MEx//6yA//+sgD/9ZtJ/+/Qq//3gRf/+XQC//SOMv+/qYr/UiQB/1QlCRuOMgAZjjQB/9i7pv/8wjn//7MA//+yAP//swH//7IB//h1Av/1nEz/78SU//h1Av/0jzP/vqiK/1MkAf9UHAkbjjIKGY80AP/Yu6b//MM4//6yAf//sgH//7MA//6zAf/5dAL/+HUD//h5C//4dAP/9I8z/76piv9SJQH/VBwJG5gyChmONQD/1rej//3Vff//swL//7IA//+zAP/+sgD/+XUC//l1Av/5dQL/+HQE//Kta/+8pon/UyUA/1QlCRuPLwAQjjQA6ZlEFP/YuKT/+uSy//zLUv/9yFP//MhT//WYRP/1mEX/9JhH/+/Glv+9pov/YTQS/1IjAOppHgARAAAAAJs3ABePNgCzjzUB/7Z8WP/Ppoz/zqaN/8+mjP+tlHX/rJR1/62Vdf+Na03/UyUB/1MjALVVHwAYAAAAAAAAAAAAAAAAAAAAAI0zAGePNAD0jzQA/480AP+ONQD/UiQB/1MkAP9SJAH/UyMB9FMkAGj///8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAACAAAABAAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjzUEOY40AL5UIgHCUyUEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkS0AHI82AKmONAH+jjUA/1MkAP9SJQH/VSIArFUiCB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJE3AGaPNQHxjzUB/440AP+PNQH/UiQA/1MlAf9SJAH/UiMB81YmAmoAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI8vDxCQNACvjjUA/441AP+PNQD/lkMQ/8qihv+tknX/XjMQ/1MlAf9TJQH/UiUA/1UiAbNUHAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPOgAnjjUB2o81AP+PNAD/jjQA/7V5VP/w5dv/+vTu/+zhxv/g0rf/impL/1IlAf9SJAH/UiUA/1IjAdxXJQYpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAizkENY40AeyONAD/jjUA/5VAD//XtJ//+vXu//r17f/72o7/8bZ6/+3hxP/s4Mf/u6WH/10xDv9TJQH/UyUB/1IjAe1TJQQ3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJE3BTOPNAHwjzUA/480AP+gUyX/6tjN//v17//67M///cI4//+yAf/5dQL/948y/+/TrP/s4Mf/18er/21DIv9SJQH/UyUA/1IjAPFbIQQ1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACaPQchjjQA6Y81AP+ONQD/pl40//Pn3//79e//+9+g//+2Df/+swH//7IB//l1Av/4dQP/+HoO//C/iP/t4cb/49W4/3dPLv9SJQH/UiUB/1MiAOtXKwcjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAnz8fCI40ANCONQH/jjQB/6RdM//16+P/+/Xv//3Vff/+sgH//rMB//6zAP//swH/+HQC//l0A//5dAL/+XQC//OvbP/s4cb/5dm8/3RPLf9SJQD/UyUB/1IlAdJmGRkKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACPNQCQjjQB/440AP+dTR//8eTa//v17v/903L//rMA//6zAP/+sgD//rMA//+yAf/4dAL/+XUD//h0Av/5dAL/+XUC//OrYv/t4Mf/4NO3/2g/HP9SJQD/UyUB/1MmAJMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkzUENI41AP2ONQD/kToH/+XOwP/79O///NeF//6zAP//swH//7MA//+yAf/+swD//7IA//h1Av/4dQP/+HUD//h0A//5dAL/+XQD//Oyc//t4Mf/zr+g/1YoB/9SJAD/UyQB/VMlBDcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACONQC+jzQB/441Af/Fl3j/+vXv//vls//+tAL//rIB//6zAf//sgH//7IB//6zAP//sgD/+XQC//h1A//5dAP/+XUC//h0Av/5dQP/+HUF/+7Glv/s4cf/o4dm/1MkAf9TJAH/UyIBwQAAAAAAAAAAAAAAAAAAAAAAAAAAlTQANY81Af+ONQH/m0sc//fu6f/68+T//bod//+yAP//swH//7IB//+zAP/+swD//7IA//6zAP/4dQL/+HQC//l1Av/4dAL/+XUC//l1Av/4dAP/94Mb/+3cvv/o3MD/Zj0b/1IlAP9SJQH/VigEOAAAAAAAAAAAAAAAAAAAAACONAGWjzUA/441AP/Mo4n/+/Xv//zSdv//sgD//7MA//+yAf/+swD//7IA//+1Bf/8y1n//7MB//l1A//4dQP/+XUD//h0Av/4dQL/+HQC//l1Av/5dQL/86pn/+3gxv+sk3X/UiUB/1IlAf9TJACZAAAAAAAAAAAAAAAAAAAAAI41AOKONAH/kTgF//Pp3v/78+b//7YR//+zAP/+sgH//7IA//6zAP/+tQn/++Cn//r17//714X/+XQC//h1Av/5dAL/+XQC//h0Av/4dAP/+XUC//h1A//5fBH/7N/A/+LXuv9XKQb/UyQA/1IiAeQAAAAAAAAAAAAAAACLLgsWjzUA/440AP+mYDb/+/Tv//vhp//+swD//7MB//6zAP//swH//7cN//rls//79O7/+vXv//v07//zr23/+XUD//l1Av/4dQL/+HQC//l0Av/5dAP/+XUD//l0A//xwo//7OHG/3dQMP9TJAH/UiUB/1seABkAAAAAAAAAAJI2BS+ONQD/jjQB/7d8Wf/79O///NV7//+yAf//swH//7IA//25E//7573/+/Tu//rmvv/9xT7/+vDf/+3hxv/zrGn/+XQD//h0A//4dAP/+XQC//l0A//5dAP/+XUD//KsaP/t4Mb/jWpN/1IkAf9TJAD/WyMAMgAAAAAAAAAAkTIFM480Af+PNAH/uYBc//v17//80nP//7IB//6yAf//sgD/+uOv//r17v/65LX//7YN//6zAf/9wTD/7Nq6/+3gx//zqGL/+XQD//l1A//4dQL/+HUD//h1A//5dAL/8qpj/+3gxv+RcVD/UiUB/1IlAf9TIAA3AAAAAAAAAACRNwUzjjQB/481AP+4gFz/+/Xu//zTcv//swH//7IA//6zAf/8vyn/+tyZ//61CP//swH//7MB//6zAP/2jS7/7dy9/+zhxv/yplz/+HQD//l1A//5dAP/+XQD//l1Av/yq2P/7eDH/5BwUP9TJAD/UiQA/1MgBDcAAAAAAAAAAJE3BTOONAH/jzUA/7mBXP/69O7//NNz//6zAf//swD//7IB//+yAf/+swD//7MB//+yAf//sgD//7MB//l1A//2jzL/7dy+/+zgxv/zpVn/+XUD//l1A//4dAL/+XUC//KqYv/s4cf/kHFQ/1IkAP9SJQH/UyAENwAAAAAAAAAAkTIAM440Af+ONQH/uYBc//v07v/903P//rMB//6yAf/+sgH//rMB//6zAP//swH//rMA//6yAP//sgH/+XUD//h1A//0kDb/7N3A/+zgxf/1oFP/+HQC//l0Av/4dQL/86pj/+zgx/+QcFH/UyUA/1MlAP9TIAA3AAAAAAAAAACRNwAzjjQA/441Af+5gFz/+vTv//3Tcv//sgH//7MA//6yAf/+swD//rIB//+zAf/+sgH//7MB//+zAf/5dQP/+XUD//h0Av/0lTv/7N/A//G1d//4dAL/+XQC//l1Av/zqmP/7OHH/5FxUP9SJQH/UyQA/1MgBDcAAAAAAAAAAJE3ADOPNAH/jzUB/7mAXP/79O7//dJy//6yAP/+sgH//7MA//6zAP//sgH//rIA//+yAf/+swD//rMA//h1A//4dQP/+XQD//h0Av/2iSf/+HUD//l0A//4dQP/+HUD//OqYv/s4Mf/kXFQ/1MlAP9TJAH/UyUENwAAAAAAAAAAkTIAM480Af+PNAD/uYFd//v07v/803L//rIB//+yAP//sgD//7IB//+yAP//swH//rIA//+zAP//sgD/+HUD//l1Av/5dQP/+HUD//l1A//4dAL/+HUC//h0Av/5dQP/8qpi/+zgxv+QcVD/UiUB/1IlAf9TIAQ3AAAAAAAAAACRMgUzjzQB/480Af+4gV3/+/Xu//3Xgf/+swH//rMB//+zAP/+sgD//7IB//+zAP/+sgH//rMA//6zAf/5dQL/+HQC//h1Av/5dAP/+HQD//h1Av/4dAL/+HQD//l1A//ysW7/7eDG/5BwUf9TJAH/UyUA/1MlADcAAAAAAAAAAJE3ADOONAD/jzQA/7J0T//69O//+vTs//zZh//+tQn//7MA//+zAP/+sgH//rIB//6zAP//swD//7IB//l1Av/5dQP/+XUD//h0Av/5dAL/+HUC//h0A//5eQn/8rJz/+3hxf/t4Mb/h2RF/1IlAP9SJAD/UyUENwAAAAAAAAAAkTcFM441Af+ONQD/jjUA/7N0Tv/y593/+/Tv//rqxv/9viz//7MB//6yAf/+sgH//rIA//+yAP//sgD/+XQD//h1Av/4dQL/+XQD//h1A//5dQP/9ogp/+/Opv/t4cb/4tW4/4ZkRf9SJAD/UyQB/1IkAf9TIAQ3AAAAAAAAAACUKhUMjzYBqY40Af+ONQH/jzUA/5pJGP/dvq3/+/Xu//vy6P/74Kf/++Gk//rgpf/74KT/+uGk//vgpP/xv4n/8b6J//C+iP/wv4j/8L+I//HAiv/t38P/7ODG/8Oukv9lORf/UiQB/1IkAP9TJAD/VCMBrVskAA4AAAAAAAAAAAAAAAAAAAAAjTcAXI80APCONQH/jzQB/483Af+9hmX/9u7m//v07v/69O//+vTv//r17v/69e7/+vTv/+3hxv/t4Mf/7eDG/+zgxv/t4Mb/7eDH/+bbwP+Xdln/VSQC/1MlAf9SJQH/UyMA8VUiAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmTMAHo40Ab+ONAD/jzQA/481AP+aSRj/olgt/6NYLP+iWSz/o1kt/6JYLP+jWC3/bkYk/29GJP9uRyX/b0cl/29HJP9uRiX/YjgX/1IkAP9TJQH/UyQB/1IhAcNVLgchAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf38AAo02AnWPNAH4jjUA/441Af+ONQD/jzQB/440Af+ONQD/jjQB/480Af9TJQH/UiQB/1MlAf9TJAH/UyUA/1IlAP9TJQD/UyQA/1IjAPlVJgB4VQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAxBS6PNADSjjQB/440Af+PNQH/jzUA/481Af+PNAH/jjQA/1IkAP9SJQD/UiUB/1IkAf9TJAD/UiUB/1IlAf9TIgDVXSkFMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAADAAAABgAAAAAQAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKo/AAyPNQQ+kDYAuFUkAb1VJgBCYicTDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/KgAGlDUAQ48yAaKONADtjjUB/1MlAf9SJADvUyUBpVMkA0ZtSCQHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJYtDxGONAGTjjQA6Y81Af+ONAH/jzQA/1MlAf9TJAD/UyUA/1IiAepUIwCXXTUAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACZMxkKkjgDRI40AdmPNQD/jjQA/481Af+PNQH/jzQA/1IkAf9TJQH/UiUB/1MlAf9TJQH/VSIA3VUjA0hzLhcLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI0vCRuONgGNjjQB8I80Af+PNQD/jjQB/441Af+ONgD/oVYq/3FGJv9UJQL/UyUB/1MlAP9TJQH/UyUB/1IjAPJWIwGRVyMIHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkzMALY81Ac2ONAD5jzUA/480AP+ONAH/jjUB/5M9Cf/Aj27/7N3O/9nJr/+cgGP/WS0L/1MlAP9SJQD/UiQA/1MkAP9TIwD6VSIA0V0pADEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJkzAAWPNgBQjjUA6I80Af+PNQD/jjQA/440Af+TOwn/plwz/+DIuP/69O//+/Tv/+zgx//s4cf/zbue/3dPL/9ZKgj/UiQA/1MlAf9TJAD/UyQB/1IjAetVJANUmTMzBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfz8ABI81AG6ONQHljzUB/481Af+PNQH/jjUB/5hHF//GmXz/8+bd//v07//69e7/+/Hi/+3cvf/s4Mf/7eHH/+DVuf+liWr/YzYV/1MkAf9TJQH/UiUA/1IkAf9SJAHnVSYCcWYzMwUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABmMwAFjzYBh441APSONQH/jjQB/440AP+ONAH/oFYp/+TNvP/28Oj/+/Xv//v17v/757v//MI6//WONP/uy5//7eHF/+3hx//o3cH/z72h/25GJ/9SJQH/UyQA/1MkAP9TJQD/UyQB9VMmAIxVKgAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8/HwiSNAB6jjQB9o80AP+PNAD/jjUA/5A4Bf+wc0z/8OTZ//r17//69O7/+vDc//3Zhv//tg7//7IA//l0A//4fBH/8rNy/+3ZuP/t4cf/7eDG/97Stv+GY0L/VykE/1MkAP9SJAH/UyQA/1MkAfdUJgJ+Xx8fCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEzAm2ONADujjUB/440Af+PNQH/kTkE/7+Ka//u4tn/+vXu//r17f/757n//MdG//+yAP/+sgD//rIB//l1Av/5dQP/+XQC//WXP//uyZr/7eHF/+3hx//f0LX/mXpa/1YoB/9TJAH/UyQA/1IkAP9SJQHvVSQEcf8AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjjUCW480APOONQD/jjQA/440AP+QOwb/y5+C//bt5v/69O//+/Tu//vhpf/9ux3//rMA//6yAf//sgH//rMB//h1Av/4dAL/+XQD//h0Av/3gx3/8MGN/+3gxv/s4cb/59u//6iPcP9YKQb/UyUA/1MlAf9TJQH/UyIB9FUlAmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAGPNQA5jzQA5o41AP+PNQH/jzUA/5M7Cf/FlHb/9u7p//r17//78uX/+tmJ//+0A//+sgH//7MA//6yAf//sgH//7IB//h0A//5dAP/+HUD//h1A//4dQL/+XUF//C1dv/t3L7/7eHH/+ncwf+hhGb/WCsJ/1IkAP9SJQH/UiUB/1IlAOdVKgQ8/wD/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJEwDBWONQC2jjQB/o81Af+ONQH/jjUA/72IaP/z6eD/+vTu//vy4//80nT//rcL//+yAP//swH//rMA//+yAf//swD//7IB//h0A//4dAL/+XUD//l1Av/5dAL/+HQD//h5Cv/yq2X/7N29/+3gxv/i17v/mXpa/1MlAv9SJAD/UiUB/1IlAP5UIwG5aC4AFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI81AHyPNAH6jjUB/480Af+PNAH/tXhU//Xt5f/69e7/+/Tv//zTcf/+tAj//rIA//6zAP/+swH//rIB//6zAP//sgH//rMA//h0A//4dAL/+HQD//l1A//5dAP/+HUD//h1A//5eQv/86tj/+zhxv/t4Mf/5dm+/41qSv9TJAH/UiQA/1MlAf9TIwD7VSMAgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjzUAMI81AfmONQD/jjUB/442AP+kXTP/7uDX//r17//68uj//dZ///6yAf//swH//7MB//+zAf//sgH//rMA//+yAf/+sgH//7IB//h0Av/5dQP/+HUC//h0A//4dAP/+HUC//h0A//5dAL/+XQD//Kwb//s3sH/7eHG/93Psv91Tiz/UyUC/1MkAP9SJAH/UiMA+lMnADQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACIMxEPjjYAuI80AP+ONQD/jjQA/5ZCEf/WtqL/+PXt//r07f/63Zj//7cP//+yAP//sgD//rMA//6yAf/+swH//7IA//+yAP/+swH//rIB//l0Av/5dQL/+XUC//l0A//5dAP/+HUD//h1Av/4dAL/+HQD//h6Dv/xuoL/7eHE/+rgxP+9p4n/XjAP/1MkAf9TJQD/UiQB/1MkAbtPHw8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACOMwNUjjUA8I41Af+PNQH/jjQB/7h/XP/38Oj/+vTu//vszP/9vSP//rMA//6zAf//sgD//rIB//+yAf/+sgH//rIA//6yAf/+swD//rIA//h1Av/5dAL/+XQD//l1Av/4dQL/+XUD//l0A//5dQL/+XUC//l0Av/3hSH/7NKs/+zhxv/o3MH/kHBQ/1MkAP9TJQH/UyUB/1IiAfFUIwBXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJQ/AAyONQCjjjQB/441AP+ONQD/mEUU//Hk2v/69O7/+vPo//zJTP//sgD//7IA//6zAf/+swH//7MA//+zAP/+sgH//rMA//+yAf/+swD//rIA//h0A//5dAL/+XUC//l1Av/5dAP/+XQD//h1Av/5dAP/+HQC//h0A//5dQL/9JlF/+zfw//t4Mb/4NK2/2A0Ev9TJQH/UiUA/1IlAP9UIwGmTicTDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIwzBiiONQHljjUA/480Af+RNwD/y6CH//r17v/69O7/+9uS//6yAf/+sgH//7IA//+yAP/+sgH//rIB//6zAf//sgH//7MA//60Bf/+sgH//rMA//l0A//4dAP/+XQD//l1A//5dAP/+XQC//h1A//5dQL/+HUD//l1Av/5dQP/+HUF//C5fv/s4Mb/7eDG/6qRc/9VJQL/UiUA/1MkAf9SJQHnVyUGKQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI00AGqONAH+jzQB/441AP+fUyT/7NzQ//v17//67tX//L8o//+yAP/+swH//rMB//6yAf/+swH//rMB//6zAP/+sgH//LcN//vdmP/9xUH//rIA//h1Av/5dQP/+XQD//l1A//4dQL/+XUC//h1A//5dQP/+HQD//h0A//5dQL/+XUC//eGJP/t17L/7eDH/9jIrf9sQyH/UyUB/1MkAf9TJAD+VSUCbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAI80Ab2ONQD/jjUA/480Af+7g17/9u/n//r17//82pH//7cI//+zAP/+sgD//rIB//6zAf/+sgD//rMA//6yAf/8ux3/+uSz//r17v/76sn//cAw//h0A//4dAP/+HUC//l1Av/5dAP/+HQC//h1A//5dAP/+HQD//h1Av/4dAP/+HQC//h4Cv/xtnr/7ODE/+fawf+Sc1L/UiUC/1IkAf9TJQH/UyIAwQAAAAAAAAAAAAAAAAAAAAAAAAAAmTMZCo80APSPNQD/jzUB/5I9Cf/RqZH/+vXv//rz4v/8ylL//rIB//+yAP/+swH//rMB//+zAf/+sgH//7IA//28JP/74qz/+vXt//v17//69O7/++rG//aOM//5dAL/+XUD//h0Av/4dQP/+XQC//l0Av/5dQL/+XQC//h1A//5dQP/+HUD//h0A//1nEn/7Ny9/+zgxv+wmHr/WSsI/1IkAP9TJQD/UyQA9moqAAwAAAAAAAAAAAAAAAAAAAAAjzUFMI41AP+ONAH/jjQB/5hGFP/hxrf/+/Xu//rt0//8vCX//rIA//+zAP/+sgH//rIA//6yAP/+sgD//b0j//vrx//79O3/+vXv//v07//79e7/+/Tu/+/Rq//3jzD/+XQC//h1A//5dQP/+XUC//l1Av/5dAP/+HUC//l0A//4dAL/+XUC//h0A//3hyP/7dWw/+3hxv/Jt5n/YTQT/1MlAP9TJAH/UiUB/10nADQAAAAAAAAAAAAAAAAAAAAAkDIDTI40Af+PNQD/jzUB/51MHP/r2sz/+/Xv//rqyf/+tQf//rIA//6yAP/+swD//7MB//+0A//8wDP/+uvN//v17//69O7/+uzQ//3IT//65rb/+vXs/+zgx//uzaD/94Yk//l1Av/5dQL/+HQC//l0Av/5dQL/+HQD//h1A//5dQP/+HUC//l0A//5eAr/79Co/+3hx//ZyK3/ZzsY/1MlAf9TJQH/UiUA/1YmA1AAAAAAAAAAAAAAAAAAAAAAkDMDVY80AP+ONAH/jjQA/5xPH//v3tT/+vXv//vpwf//sgH//7MB//6yAP/+sgH//rMA//3FPv/76cL/+/Xv//r07//657j//MEy//+zAf/9wS//+ue9/+zhx//s4cb/7suf//aLK//5dAL/+XQC//h1A//4dQP/+XUD//l0A//4dAP/+HUC//h0A//4dAP/786k/+zhx//dz7P/Zj0b/1MkAf9SJQH/UyQA/1UiAloAAAAAAAAAAAAAAAAAAAAAkTUAVo41AP+ONQD/jjQA/5xPHv/v4dX/+/Xu//vmwf//sgH//7MB//6zAf/+sgD//rMB//rdkv/69O7/+vTu//row//9vyn//7MA//6yAP/+sgD//7wh/+7QqP/s4cb/7ODG/+/PpP/3iCj/+XUC//h1A//5dQL/+XQD//h0A//4dQL/+XUD//h0Av/5dAP/7s6l/+zhxv/czrL/aD8c/1MkAf9SJQD/UiQA/1UhAFwAAAAAAAAAAAAAAAAAAAAAjjUAVo41AP+PNAD/jjUB/5xOHv/v4NX/+/Tu//rmwP//sgD//rIA//6zAP/+swD//rIB//65F//74q//++e4//y5Fv//swH//7MB//6yAP/+sgH//rIA//eEIf/uzaP/7eDE/+zhxv/vyZj/9oUe//l1Av/5dAP/+XQC//l1A//5dQL/+XQC//h0Av/5dQL/7s6k/+3hxv/cz7P/aT4c/1IlAf9TJQH/UiQA/1UhAlwAAAAAAAAAAAAAAAAAAAAAkTUAVo80Af+PNQH/jzUA/51OH//v4dX/+vXv//vnwf/+swD//7IA//+zAf//sgD//7IB//6yAf/9vCP//LkX//6zAP/+sgD//7IB//6yAP//swH//rIB//h0A//3jjD/786m/+3gxv/t4Mf/7saW//aGIv/5dAL/+HUD//h0A//4dQP/+XQD//l1A//5dAP/7s6l/+zgx//dzrL/aT8d/1MkAf9SJQD/UiUB/1UhAFwAAAAAAAAAAAAAAAAAAAAAkTUAVo40Af+ONAH/jjQB/51PH//v4NT/+vTu//rnwf//sgD//rIB//6yAP//swH//7MB//+yAf/+sgD//7MA//+yAf//sgD//rIA//6zAf//swD//rMA//h1A//5dAL/94kn/+zUsP/t4cf/7ODG/+7Knf/2hCH/+XQC//h1Av/4dAL/+HUC//l1A//4dAL/7s+k/+zhxv/dzrP/aD8c/1IkAP9TJQH/UiUB/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjUCVo81Af+PNAD/jjUB/5xPH//u4dX/+vXu//vnwP/+swH//rIA//6yAP//sgH//7MA//+zAP//sgH//rIB//+zAf//swD//rMA//6yAP/+sgD//rMA//h0A//5dAL/+XUD//eIKP/v06v/7eHF/+zhx//ww47/+YAb//h0A//4dAL/+HUC//h0Av/4dQL/78+k/+3gxv/czrL/aT4d/1IkAP9TJAD/UyQA/1UhAFwAAAAAAAAAAAAAAAAAAAAAkTIAVo40Af+ONQD/jzUA/5xPHv/u4dX/+/Tu//vnwf/+swH//rIB//+zAP/+sgD//7IB//+zAP/+sgD//rMB//+zAf//sgD//rIB//+zAf/+sgD//rIB//h1Av/5dAP/+HUD//l1Bf/1kjn/79Ks/+zhxv/s4MT/87Nz//h0A//5dQP/+XUC//h0Av/5dAP/786k/+3gx//czrL/aD8c/1MlAf9SJAH/UyQB/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjUCVo41AP+ONQH/jzUB/5xOHv/v4NT/+/Tv//rnwf/+swD//7IA//6yAP//swH//7MB//6yAf//swH//7IA//+yAP/+swD//7MB//+zAP//sgH//rMB//h0Av/4dQP/+XQD//h1A//4dQT/94wu/+zZuP/v06r/94wv//l1Av/5dQL/+HUD//h1Av/4dQL/7s+k/+zhx//dzrL/aD8d/1IlAf9TJQH/UiQB/1UhAlwAAAAAAAAAAAAAAAAAAAAAkTIAVo81Af+PNAD/jjUB/5xOH//u4NT/+vXu//rmwf/+sgD//rIA//+yAf//sgD//rIA//+zAP/+swH//7MB//+yAf//sgH//rIA//6zAf//swH//7MA//l1Av/5dAL/+HUC//h0Av/4dQP/+XUD//aJJ//2jzP/+HUD//l1A//4dQP/+HQD//l0Av/5dAL/78+k/+zhx//cz7L/aT8c/1IkAP9TJAH/UyUB/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjICVo81Af+ONQH/jjUB/5xPH//u4NX/+/Tu//rnwf/+sgH//7IB//6zAP/+sgD//rIB//+yAP/+swH//rIA//+zAP//sgD//rIA//+yAf/+swD//7MB//h1A//5dQL/+XQD//h0Av/5dQL/+XUD//l0A//5dAL/+HQD//h1A//5dAL/+HUC//h1Av/5dAP/7s6l/+zhxv/dzrL/aD8c/1MlAf9SJQD/UyUA/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjICVo40AP+ONAD/jjQA/51OHv/u4dX/+vTv//rmwP//sgD//7IB//+zAf//sgD//7MB//6yAf//sgD//rIA//6yAf//sgH//rIA//+zAP/+sgD//rMB//h1Av/4dAL/+XQD//l1Av/4dQP/+XQD//h0A//5dQP/+HQD//l1Av/4dAL/+XUD//l0A//4dQP/78+l/+3hxv/cz7L/aD4d/1MlAP9TJAH/UiQA/1UhAFwAAAAAAAAAAAAAAAAAAAAAkTICVo41Af+ONQD/jzQA/5xPH//v4dT/+/Xv//vow///tQT//rMB//6yAP/+swD//rIA//6zAf/+sgD//7IB//6yAP//sgD//7MB//6yAP/+sgH//7MA//l0Av/5dAL/+XQD//l1A//4dAP/+HQD//h1Av/4dQP/+HUD//l1A//5dAP/+XUC//l1A//4dwT/7s+n/+3hx//czrP/aT4d/1MkAP9SJAH/UyQB/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjUCVo41AP+PNQD/jjUB/51OH//v4dT/+/Xv//rw3P/8z2L//7YL//6yAP//sgD//rMB//+zAP/+swH//rMB//6yAP//sgD//7IA//6zAf//sgD//rIB//h0A//5dAP/+HQD//l0Av/4dQP/+XQC//h1A//5dAP/+HQD//l1A//5dAL/+XUC//h5Cv/zolT/7Nu4/+3gx//czrP/aT4c/1IkAP9TJAD/UyQB/1UhAFwAAAAAAAAAAAAAAAAAAAAAjjICVo40Af+ONAD/jjQB/5lJF//jzL3/+/Tv//r07v/68uX/+uCi//y4FP//sgD//rMB//6yAP//sgD//7MB//6yAP/+sgH//7IA//6yAP//sgH//rIA//h1A//5dQL/+HQD//h1Av/4dAL/+XQD//h0Av/5dAL/+HQD//h0Av/4dQP/+X8U//HBi//t3Lz/7ODG/+zgxv/OvaD/YzcV/1IlAP9TJAH/UiUB/1UhAlwAAAAAAAAAAAAAAAAAAAAAjjUCVo40AP+PNAH/jjQB/440AP+dTh7/2Lmk//bs5P/79O//+/Xu//vt0f/8x0b//rQH//6zAP//sgD//7IA//+zAf/+sgD//7MB//+yAP/+sgD//rIA//h0Av/4dQL/+HQD//l0A//5dAP/+XUC//l1A//4dAP/+XUD//h5CP/0lj//7tWu/+zgxv/t4cf/59q+/7+rjf9oPhz/UyQA/1MkAf9TJAD/UiUA/1UhAFwAAAAAAAAAAAAAAAAAAAAAjzMAQI80APWPNQH/jjQA/440AP+ONAD/kjwI/7uEY//o1sj/+vTu//r17v/77tz//NeC//zAMP/9vyz//L4t//2/LP/8viz//b8s//2/LP/8vy3//b4t//eJJ//3iCb/9ogm//eJJv/3iSb/9ogn//eJJv/2iSb/9osr//OxcP/t2Lb/7eHH/+3hxf/UxKn/lXVV/1stC/9TJQD/UiUA/1IlAP9TJQD/UyQB9lUkA0UAAAAAAAAAAAAAAAAAAAAAkUgkB5E0AE2PNQDdjzUA/480Af+ONAD/jjUA/5A3A/+gVyv/3MGu//r17v/79e7/+vXs//vv1v/77tb/+u7X//rv1//67tb/+u7X//rv1//779f/++7W/+zVsf/s1LH/7dSw/+3VsP/t1LD/7dWw/+3Usf/s1bH/7dez/+zgxP/t4cf/7OHG/8eylf9vSSb/VCcF/1MkAP9SJAH/UiUA/1MlAf9TJADgVSUAUV8fAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACSMwAojDUBuY40APaONAH/jjQA/440AP+PNQD/kTYD/8KTdf/w5dv/+/Tu//v07//69e//+/Xv//r07v/69e7/+/Xv//r07//79e//+/Xv/+3gx//s4cb/7eDH/+3hxv/s4Mb/7eHG/+zhx//s4Mf/7eHH/+vgxf/h07f/oIVm/1UnBf9SJQD/UiQA/1IkAf9SJAD/UiUA91IjAb1eIwUrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfzYADpAzAHGPNQHcjjQA/o80Af+ONQH/jjQB/5E5Bf+ta0P/1LGb/9i5pP/YuKX/2Lmk/9i5pf/ZuKX/2bmk/9m5pP/YuaT/2bml/72kiP+9pIn/vKWI/7ylif+8pIn/vKSJ/7ylif+9pIj/vaWJ/7afgf9/Wjv/VygE/1MkAP9TJAD/UiQA/1IlAf9SIgHeVCUCdVUiEQ8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8/AASRNwAzjzQAxI41Af+PNQH/jzUB/441AP+PNwD/lT4M/5dAD/+XQQ//lkEP/5dBDv+WQA//lkEP/5ZBD/+WQQ7/l0AO/1wxDf9cMQz/XTAN/10xDf9dMQz/XTAM/1wwDf9cMQ3/XDEM/1ovCv9VJQL/UiQB/1MlAP9TJAD/UyQA/1ImAclTJQQ3Pz8/BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfyoqBo80AYmPNADtjzQA/o81Af+ONQD/jzQA/480Af+PNAH/jzQB/440Af+PNAH/jzUB/441AP+PNAD/jjQB/1MkAP9SJQH/UiQB/1MkAf9TJAH/UyUB/1MlAf9TJQH/UiQA/1IlAf9TJAD/UyQB/1IkAP5SJQHuViUAjl8fAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8qAAaPNwBOjzUAxY41AP+ONQD/jjUA/480Af+ONQD/jzQA/440AP+PNAH/jjUB/480Af+PNAH/jzUA/1IlAP9TJQD/UyQB/1MkAf9TJAD/UiQB/1IkAf9SJAD/UyUA/1IlAf9TJAD/UiQA/1IiAMlTJQBSVVUABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/AAACijUAGI81AYuPNQD4jzQB/480Af+ONQH/jzUA/440AP+PNQD/jjQA/480Af+PNQD/jjQB/1IlAP9TJAH/UyQB/1IkAf9TJQH/UyQB/1IlAf9SJQH/UyQB/1MkAf9TIgD6VSIAklEoChl/AAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==`

	// Decode the base64 data
	iconData, err := base64.StdEncoding.DecodeString(iconBase64)
	if err != nil {
		fmt.Println("Error decoding icon data:", err)
		return nil
	}

	return iconData
}

// hideConsoleWindow hides the console window for the Go program on Windows
func hideConsoleWindow(cmd *exec.Cmd) {
	cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true}
}

func stopCommand() {
	// Build and run the stop command: mieru.exe stop
	cmdStop := exec.Command(filepath.Join(dir, ExecutableName), "stop")
	cmdStop.Dir = dir

	// Hide the console window for the Go program
	hideConsoleWindow(cmdStop)

	err := cmdStop.Run()
	if err != nil {
		fmt.Println("Error running stop command:", err)
	}
}

func openFolder() {
	err := exec.Command("explorer", dir).Start()
	if err != nil {
		fmt.Println("Error opening folder:", err)
	}
}

func loadStartOnBoot() {
	key, err := registry.OpenKey(registry.CURRENT_USER, RegistryKey, registry.READ|registry.WRITE)
	if err != nil {
		fmt.Println("Error opening registry key:", err)
		return
	}
	defer key.Close()

	exePath, err := os.Executable()
	if err != nil {
		fmt.Println("Error getting executable path:", err)
		return
	}

	val, _, err := key.GetStringValue(AppName)
	if err == nil {
		// Mieru value exists in registry
		if val != exePath {
			// Update registry value if the executable path is different
			err = key.SetStringValue(AppName, exePath)
			if err != nil {
				fmt.Println("Error updating registry value:", err)
			}
		}
		startOnBoot = true
	} else if err == registry.ErrNotExist {
		// Mieru value does not exist in registry, set startOnBoot to false
		startOnBoot = false
	} else {
		fmt.Println("Error reading registry value:", err)
	}
}

func saveStartOnBoot() {
	key, err := registry.OpenKey(registry.CURRENT_USER, RegistryKey, registry.WRITE)
	if err != nil {
		fmt.Println("Error opening registry key:", err)
		return
	}
	defer key.Close()

	exePath, err := os.Executable()
	if err != nil {
		fmt.Println("Error getting executable path:", err)
		return
	}

	val, _, err := key.GetStringValue(AppName)
	if err != nil || val != exePath {
		if startOnBoot {
			err = key.SetStringValue(AppName, exePath)
			if err != nil {
				fmt.Println("Error writing registry value:", err)
			}
		} else {
			err = key.DeleteValue(AppName)
			if err != nil {
				fmt.Println("Error deleting registry value:", err)
			}
		}
	}
}

func updateStartOnBoot(startOnBootItem *systray.MenuItem) {
	if startOnBoot {
		startOnBootItem.Check()
	} else {
		startOnBootItem.Uncheck()
	}
}
